apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-app

spec:
  replicas: 3
  selector:
    app: nginxtest
  template:
    metadata:
      name: nginxtest
      labels:
        app: nginxtest
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8083
